apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Chart.Name }}
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000